# Site settings
title: Per Scribo Ad Astra
header-img: img/merlin.jpg
email: miketwo@gmail.com
copyright_name: Michael Ricks-Aherne
description: "Random thoughts. Some of them good."
baseurl: ""
old_site: "https://miketwo-original.appspot.com"
url: "http://miketwo.net/blog"
twitter_username: miketwo345
github_username:  miketwo
# facebook_username:  ""
email_username:  miketwo@gmail.com

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

plugins: [jekyll-paginate, jekyll-feed]
