# Site settings
title: MikeTwo's Blog
header-img: img/home-bg.jpg
email: miketwo@gmail.com
copyright_name: Michael Ricks-Aherne
description: "Random thoughts..."
baseurl: ""
url: "http://yourdomain.com"
twitter_username: miketwo345
github_username:  miketwo
facebook_username:  ""
email_username:  miketwo@ygmail.com

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

plugins: [jekyll-paginate, jekyll-feed]
